package serialize;

/**
 * This error class is responsible for managing errors responsible with invalid or corrupted game
 * file loading
 *
 */
public class LoadErrorException extends Exception {

    /**
     * Added a default serial version for this exception, generated by eclipse
     */
    private static final long serialVersionUID = -6830267290758491047L;

    public LoadErrorException () {
        super();
    }

    public LoadErrorException (String message) {
        super(message);
    }

    public LoadErrorException (Throwable cause) {
        super(cause);
    }

    public LoadErrorException (String message, Throwable cause) {
        super(message, cause);
    }

    public LoadErrorException (String message,
                               Throwable cause,
                               boolean enableSuppression,
                               boolean writableStackTrace) {
        super(message, cause, enableSuppression, writableStackTrace);
    }

}
